### ISSUE TITLE
Request: Pack Folders

### ISSUE THREAD

**Issue by esheyw** [velara/MercenaryMarketVolume1#30]
Could you please update the manifest so the various compendia come inside a folder? Having unfoldered compendia looks weird now that the system has theirs managed 😅

**Comment by velara** [comment]
For sure. I'll fix that in the next update. 

I had got it all set up inside a single Mercenary Marketplace folder when I first updated it, but discovered when working on another module after the fact that the method I'd been using only worked locally. Egg meet face. I've since learned the proper method, but forgot that I hadn't already done so with the module since my own copy looked perfect.
