### ISSUE TITLE
Winged Tiger Form statistics

### ISSUE THREAD

**Issue by jonathanmclaus** [velara/MercenaryMarketVolume1#31]
The statistics for the Winged Tiger Form of the Mercenary Druid don't compute correctly. For example, this is a freshly imported [9-10] version with the effect listed in its Actions applied:

![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/5731591/71bfd29e-cf6a-4723-8cbe-ff8161587484)

The AC and Athletics are incorrect.

**Comment by velara** [comment]
Thanks for the report. I've tracked down the issue. Athletics used a rule element from burning tiger form, which wasn't designed to handle lower levels, and the logic governing the AC rule element I had been using appears to have changed. I'll clean them up and it should be fixed in the next v11 release.
